# This is a Docker Compose file for setting up the lens-stack environment.

name: lens-stack
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  redis_data:
  searxng_data:
